default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: accounts_user
  password: password

development:
  <<: *default
  database: accounting

test:
  <<: *default
  database: accounting_test
  username: accounts_user_test
  password: password

production:
  <<: *default
  database: accounting_prod
